export const environment = {
  production: true,
  prefillLoginForm: false,
  displayProcessesInfo: false,
  debugBlockUnblockUI:false,
  apiURL: "https://api-demo.merchmgt.com/",
  apiURLForFiles: "https://file-api-demo.merchmgt.com/",
  numberOfSecondsBetweenRefreshOfMessages: 120,
  numberOfSecondsBetweenChecksOfVersion: 120,
  frontEndVersion:"2020-06-03.01",
  jwt_name: "merchmgt_jwt",
  defaultNumberOfResults:50,
  numberOfResultsForDeals: 50,
  numberOfResultsForDesigns: 25,
  numberOfResultsForForumMessages: 40,
  numberOfResultsForDashboard:10,
  hideTrademarksModule:false,
  hideSalesReportsModule:false,
  maxFileSizeInMByteForRasterImages:10,
  maxFileSizeInMByteForOtherFiles:50,
};
