export const environment = {
  production: true,
  prefillLoginForm: false,
  displayProcessesInfo: false,
  debugBlockUnblockUI:false,
  apiURL: "https://api-medleg.orfead.org/",
  apiURLForFiles: "https://api-medleg.orfead.org/",
  numberOfSecondsBetweenRefreshOfMessages: 120,
  numberOfSecondsBetweenChecksOfVersion: 120,
  frontEndVersion:"2021-06-08.02",
  jwt_name: "orfead_jwt",
  defaultNumberOfResults:50,
  numberOfResultsForDeals: 50,
  numberOfResultsForDesigns: 25,
  numberOfResultsForForumMessages: 40,
  numberOfResultsForDashboard:10,
  hideTrademarksModule:false,
  hideSalesReportsModule:false,
  maxFileSizeInMByteForRasterImages:10,
  maxFileSizeInMByteForOtherFiles:50,
};
