export enum TRADEMARK_TYPE {
    combined = 1,
    word = 2,
    other = 3,
    figurative = 4,
    general_mark = 5,
    _3d = 6,
    _3dshape	= 7,
    colour = 8,
    combination_of_colours = 9,
    hologram = 10,
    kennfaden = 11,
    motion = 12,
    multimedia = 13,
    olfactory = 14,
    packing = 15,
    pattern = 16,
    position = 17,
    sound = 18,
    stylized_characters = 19,
    undefined = 20
}